# Generated by Django 5.1.1 on 2024-10-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=255)),
                ('regiao_turistica', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('subtipos', models.CharField(max_length=255)),
                ('nome_oficial', models.CharField(max_length=255)),
                ('nome_popular', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstruturasAoLongoDaVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OutrosServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostoDeCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrganizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rodovia',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apidjango.base')),
                ('juridiscao', models.CharField(max_length=50)),
                ('natureza', models.CharField(max_length=50)),
                ('extensao_rodovia_municipio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faixas_de_rolamento', models.CharField(max_length=50)),
                ('pavimentacao', models.CharField(max_length=50)),
                ('pedagio', models.CharField(max_length=10)),
                ('municipios_vizinhos_interligados_rodovia', models.TextField()),
                ('inicio_atividae', models.DateField()),
                ('whatsapp', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('de_acesso', models.CharField(max_length=10)),
                ('turistica', models.CharField(max_length=10)),
                ('poluicao', models.CharField(max_length=10)),
                ('poluicao_especificacao', models.TextField()),
                ('lixo', models.CharField(max_length=10)),
                ('lixo_especificacao', models.TextField()),
                ('desmatamento', models.CharField(max_length=10)),
                ('desmatamento_especificacao', models.TextField()),
                ('queimadas', models.CharField(max_length=10)),
                ('queimadas_especificacao', models.TextField()),
                ('inseguranca', models.CharField(max_length=10)),
                ('inseguranca_especificacao', models.TextField()),
                ('extrativismo', models.CharField(max_length=10)),
                ('extrativismo_especificacao', models.TextField()),
                ('prostituicao', models.CharField(max_length=10)),
                ('prostituicao_especificacao', models.TextField()),
                ('ocupacao_irregular_invasao', models.CharField(max_length=10)),
                ('ocupacao_irregular_invasao_especificacao', models.TextField()),
                ('outras', models.CharField(max_length=10)),
                ('outras_especificacao', models.TextField()),
                ('estado_geral_de_conservação', models.CharField(max_length=20)),
                ('observacoes', models.TextField()),
                ('referencias', models.TextField()),
                ('nome_pesquisador', models.CharField(max_length=255)),
                ('telefone_pesquisador', models.CharField(max_length=255)),
                ('email_pesquisador', models.CharField(max_length=255)),
                ('nome_coordenador', models.CharField(max_length=255)),
                ('telefone_coordenador', models.CharField(max_length=255)),
                ('email_coordenador', models.CharField(max_length=255)),
                ('estruturas_ao_longo_da_vida', models.ManyToManyField(to='apidjango.estruturasaolongodavia')),
                ('outros_servicos', models.ManyToManyField(to='apidjango.outrosservicos')),
                ('posto_de_combustivel', models.ManyToManyField(to='apidjango.postodecombustivel')),
                ('tipo_de_organizacao_instituicao', models.ManyToManyField(to='apidjango.tipoorganizacao')),
            ],
            bases=('apidjango.base',),
        ),
    ]
