# Generated by Django 5.1.1 on 2024-10-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0003_remove_rodovia_estruturas_ao_longo_da_vida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrganizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('associação', 'Associação'), ('sindicato', 'Sindicato'), ('cooperativa', 'Cooperativa'), ('sistema', 'Sistema'), ('empresa', 'Empresa'), ('outro', 'Outro')], default='associação', max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
        ),
        migrations.AddField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.ManyToManyField(to='apidjango.tipoorganizacao'),
        ),
    ]
