# Generated by Django 5.1.1 on 2024-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0004_tipoorganizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
        ),
        migrations.DeleteModel(
            name='TipoOrganizacao',
        ),
        migrations.AddField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.CharField(choices=[('associação', 'Associação'), ('sindicato', 'Sindicato'), ('cooperativa', 'Cooperativa'), ('sistema', 'Sistema'), ('empresa', 'Empresa'), ('outro', 'Outro')], default='associação', max_length=120),
        ),
    ]
