# Generated by Django 5.1.1 on 2024-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0005_remove_rodovia_tipo_de_organizacao_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.CharField(choices=[], default='associação', max_length=120),
        ),
    ]
