# Generated by Django 5.1.1 on 2024-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0006_alter_rodovia_tipo_de_organizacao_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.CharField(choices=[('associação', 'Associação'), ('sindicato', 'Sindicato'), ('cooperativa', 'Cooperativa'), ('sistema', 'Sistema'), ('empresa', 'Empresa'), ('outro', 'Outro')], default='sindicato', max_length=120),
        ),
    ]
