# Generated by Django 5.1.1 on 2024-10-30 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0007_alter_rodovia_tipo_de_organizacao_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números e espaços.', regex='^[\\w\\sáéíóúãõâêîôûçÁÉÍÓÚÃÕÂÊÎÔÛÇ]+$')]),
        ),
    ]
