# Generated by Django 5.1.1 on 2024-10-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodovia',
            name='estruturas_ao_longo_da_vida',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodovia',
            name='outros_servicos',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodovia',
            name='posto_de_combustivel',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.TextField(),
        ),
    ]
