# Generated by Django 5.1.1 on 2024-10-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0009_rodovia_estruturas_ao_longo_da_vida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodovia',
            old_name='inicio_atividae',
            new_name='inicio_atividade',
        ),
    ]
