# Generated by Django 5.1.1 on 2024-10-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0010_rename_inicio_atividae_rodovia_inicio_atividade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodovia',
            old_name='de_acesso',
            new_name='sinalizacao_de_acesso',
        ),
        migrations.RenameField(
            model_name='rodovia',
            old_name='turistica',
            new_name='sinalizacao_turistica',
        ),
    ]
