# Generated by Django 5.1.1 on 2024-10-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0011_rename_de_acesso_rodovia_sinalizacao_de_acesso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodovia',
            old_name='estado_geral_de_conservação',
            new_name='estado_geral_de_conservacao',
        ),
        migrations.RenameField(
            model_name='rodovia',
            old_name='estruturas_ao_longo_da_vida',
            new_name='estruturas_ao_longo_da_via',
        ),
    ]
