# Generated by Django 5.1.1 on 2024-10-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0012_rename_estado_geral_de_conservação_rodovia_estado_geral_de_conservacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodovia',
            old_name='juridiscao',
            new_name='jurisdicao',
        ),
    ]
