# Generated by Django 5.1.1 on 2024-11-05 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0013_rename_juridiscao_rodovia_jurisdicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='base',
            name='criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
