# Generated by Django 5.1.1 on 2024-11-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0015_alter_rodovia_estruturas_ao_longo_da_via_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodovia',
            name='estruturas_ao_longo_da_via',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='outros_servicos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='posto_de_combustivel',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.TextField(),
        ),
    ]
