# Generated by Django 5.1.1 on 2024-11-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0016_alter_rodovia_estruturas_ao_longo_da_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='tipo_formulario',
            field=models.CharField(default='rodovia', max_length=100),
            preserve_default=False,
        ),
    ]
