# Generated by Django 5.1.1 on 2024-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0017_base_tipo_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodovia',
            name='estruturas_ao_longo_da_via',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='outros_servicos',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='posto_de_combustivel',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rodovia',
            name='tipo_de_organizacao_instituicao',
            field=models.JSONField(),
        ),
    ]
