# Generated by Django 5.1.1 on 2024-11-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0018_alter_rodovia_estruturas_ao_longo_da_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acessLevel',
            field=models.CharField(default='aprovado', max_length=22),
            preserve_default=False,
        ),
    ]
