# Generated by Django 5.1.1 on 2024-11-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0019_customuser_acesslevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Aguardando Aprovação', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='acessLevel',
            field=models.CharField(default='Pesquisador', max_length=22),
        ),
    ]
