# Generated by Django 5.1.1 on 2024-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0020_customuser_status_alter_customuser_acesslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('dataInicio', models.DateField()),
                ('dataTermino', models.DateField()),
                ('codigoIBGE', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
            ],
        ),
    ]
