# Generated by Django 5.1.1 on 2024-11-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0021_pesquisa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodovia',
            name='email_coordenador',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='email_pesquisador',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='nome_coordenador',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='nome_pesquisador',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='referencias',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='telefone_coordenador',
        ),
        migrations.RemoveField(
            model_name='rodovia',
            name='telefone_pesquisador',
        ),
        migrations.AddField(
            model_name='base',
            name='email_coordenador',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='email_pesquisador',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='nome_coordenador',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='nome_pesquisador',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='observacoes',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='referencias',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='telefone_coordenador',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='base',
            name='telefone_pesquisador',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
