# Generated by Django 5.1.1 on 2024-11-26 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0022_remove_rodovia_email_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pesquisas',
            field=models.ManyToManyField(related_name='pesquisa', to='apidjango.pesquisa'),
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='usuario',
            field=models.ManyToManyField(related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
