# Generated by Django 5.1.1 on 2024-11-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0024_base_pesquisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='base',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='base',
            name='criacao',
        ),
    ]
