# Generated by Django 5.1.1 on 2024-11-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0025_inventariacao_remove_base_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariacao',
            name='equipamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apidjango.base'),
        ),
    ]
