# Generated by Django 5.1.1 on 2024-11-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0027_inventariacao_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Equipamentos', to='apidjango.pesquisa'),
        ),
    ]
