# Generated by Django 5.1.1 on 2024-11-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0028_alter_base_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidjango.pesquisa'),
        ),
    ]
