# Generated by Django 5.1.1 on 2024-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0029_alter_base_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pesquisas',
            field=models.ManyToManyField(blank=True, related_name='pesquisa', to='apidjango.pesquisa'),
        ),
    ]
