# Generated by Django 5.1.1 on 2024-11-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0030_alter_customuser_pesquisas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pesquisas',
        ),
    ]
