# Generated by Django 5.1.1 on 2024-11-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0031_remove_customuser_pesquisas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pesquisas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='apidjango.pesquisa'),
        ),
    ]
