# Generated by Django 5.1.1 on 2024-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0032_customuser_pesquisas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pesquisas',
            field=models.ManyToManyField(blank=True, related_name='pesquisas', to='apidjango.pesquisa'),
        ),
    ]
