# Generated by Django 5.1.1 on 2024-12-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0034_pesquisa_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(default='Aguardando Aprovação', max_length=50),
        ),
    ]
