# Generated by Django 5.1.1 on 2024-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0035_pesquisa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='quantidadeLocais',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='quantidadePesquisadores',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
