# Generated by Django 5.1.1 on 2024-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0036_pesquisa_quantidadelocais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='quantidadeLocais',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='quantidadePesquisadores',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(default='Em andamento', max_length=50),
        ),
    ]
