# Generated by Django 5.1.1 on 2024-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0037_alter_pesquisa_quantidadelocais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='quantidadePesquisadores',
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='status',
            field=models.CharField(default='Não Iniciado', max_length=50),
        ),
    ]
