# Generated by Django 5.1.1 on 2024-12-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0038_remove_pesquisa_quantidadepesquisadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
