# Generated by Django 5.1.1 on 2024-12-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0041_alter_pesquisa_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
