# Generated by Django 5.1.1 on 2025-01-10 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0042_alter_pesquisa_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='nome_oficial',
        ),
        migrations.RemoveField(
            model_name='base',
            name='nome_popular',
        ),
        migrations.RemoveField(
            model_name='base',
            name='subtipos',
        ),
        migrations.AddField(
            model_name='rodovia',
            name='nome_oficial',
            field=models.CharField(default='oie', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodovia',
            name='nome_popular',
            field=models.CharField(default='oie2', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rodovia',
            name='subtipos',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
