# Generated by Django 5.1.1 on 2025-01-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0043_remove_base_nome_oficial_remove_base_nome_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaDeSeguranca',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apidjango.base')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
            bases=('apidjango.base',),
        ),
    ]
