# Generated by Django 5.1.1 on 2025-01-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0044_sistemadeseguranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemadeseguranca',
            name='email',
            field=models.CharField(default='01', max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemadeseguranca',
            name='endereco',
            field=models.CharField(default='01', max_length=255),
        ),
        migrations.AlterField(
            model_name='sistemadeseguranca',
            name='nome',
            field=models.CharField(default='01', max_length=255),
        ),
        migrations.AlterField(
            model_name='sistemadeseguranca',
            name='whatsapp',
            field=models.CharField(default='01', max_length=50),
        ),
    ]
