# Generated by Django 5.1.1 on 2025-01-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0047_contatoinfo_servicoespecializadoinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemadeseguranca',
            name='nome',
        ),
        migrations.AddField(
            model_name='sistemadeseguranca',
            name='contatos',
            field=models.ManyToManyField(related_name='sistemas_de_seguranca', to='apidjango.contatoinfo'),
        ),
        migrations.AddField(
            model_name='sistemadeseguranca',
            name='servicos_especializados',
            field=models.ManyToManyField(related_name='sistemas_de_servicos_especializados', to='apidjango.servicoespecializadoinfo'),
        ),
        migrations.RemoveField(
            model_name='contatoinfo',
            name='sistema_de_seguranca',
        ),
        migrations.RemoveField(
            model_name='servicoespecializadoinfo',
            name='sistema_de_seguranca',
        ),
        migrations.AddField(
            model_name='contatoinfo',
            name='sistema_de_seguranca',
            field=models.ManyToManyField(related_name='contatos_info', to='apidjango.sistemadeseguranca'),
        ),
        migrations.AddField(
            model_name='servicoespecializadoinfo',
            name='sistema_de_seguranca',
            field=models.ManyToManyField(related_name='servicos_info', to='apidjango.sistemadeseguranca'),
        ),
    ]
