# Generated by Django 5.1.1 on 2025-01-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0048_remove_sistemadeseguranca_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='quantidadeLocais',
        ),
    ]
