# Generated by Django 5.1.1 on 2025-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0050_pesquisa_quantidadelocais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='quantidadeLocais',
            field=models.IntegerField(default=0),
        ),
    ]
