# Generated by Django 5.1.5 on 2025-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0051_alter_pesquisa_quantidadelocais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Ativo', max_length=50),
        ),
    ]
