# Generated by Django 5.1.1 on 2025-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0053_alimentosebebidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
