# Generated by Django 5.1.1 on 2025-02-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0053_alimentosebebidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentosebebidas',
            old_name='funcionamento25',
            new_name='funcionamento24h',
        ),
        migrations.RenameField(
            model_name='alimentosebebidas',
            old_name='tabelaEquipamentoEEespaco',
            new_name='tabelaEquipamentoEEspaco',
        ),
    ]
