# Generated by Django 5.1.5 on 2025-02-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0054_base_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='quantidadeLocais',
        ),
    ]
