# Generated by Django 5.1.5 on 2025-02-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0055_remove_pesquisa_quantidadelocais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='apidjango.pesquisa'),
        ),
    ]
