# Generated by Django 5.1.5 on 2025-03-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0058_meiodehospedagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeiosDeHospedagem',
        ),
    ]
