# Generated by Django 5.1.5 on 2025-04-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidjango', '0059_delete_meiosdehospedagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(default='88994388027', max_length=25),
            preserve_default=False,
        ),
    ]
